# Generated by Django 2.1.1 on 2019-02-08 00:45

import WebAdminRadio.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('tabla', models.CharField(max_length=20)),
                ('data_nueva', models.CharField(max_length=50)),
                ('data_actual', models.CharField(max_length=50)),
                ('fecha_creado', models.DateTimeField()),
                ('fecha_modificado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concursante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premios', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Emisora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('frecuencia_dial', models.CharField(max_length=8)),
                ('url_streaming', models.CharField(max_length=150)),
                ('sitio_web', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=500)),
                ('ciudad', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('logotipo', models.ImageField(upload_to=WebAdminRadio.models.emisora_file_location)),
                ('activo', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('hora_fin', models.TimeField()),
                ('dia_fin', models.DateField()),
                ('activo', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=8)),
                ('dia_semana', models.CharField(blank=True, max_length=9, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('activo', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='frecuencia_publicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HiloChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=9)),
                ('fecha_inicio', models.TimeField()),
                ('fecha_fin', models.TimeField()),
                ('activo', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=350)),
                ('url', models.ImageField(upload_to=WebAdminRadio.models.upload_location_image)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=150)),
                ('respuesta_c', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('cliente', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=350)),
                ('url', models.CharField(max_length=150)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('imagen', models.ImageField(blank=None, upload_to=WebAdminRadio.models.upload_location_publicidad)),
            ],
        ),
        migrations.CreateModel(
            name='RedSocial_emisora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RedSocial_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=150)),
                ('correcta', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('slogan', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=250)),
                ('imagen', models.ImageField(upload_to=WebAdminRadio.models.segmento_file_location)),
                ('activo', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='segmento_horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='segmento_publicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='segmento_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.CharField(max_length=250)),
                ('activo', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono_emisora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_sugerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=350)),
                ('url', models.FileField(upload_to=WebAdminRadio.models.upload_location_video)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Segmento')),
            ],
        ),
    ]
