# Generated by Django 2.1.1 on 2019-02-08 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebAdminRadio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono_usuario',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telefono_emisora',
            name='idEmisora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Emisora'),
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='idEmisora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Emisora'),
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='idSegmento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Segmento'),
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='idTipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Tipo_sugerencia'),
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='segmento_usuario',
            name='idSegmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Segmento'),
        ),
        migrations.AddField(
            model_name='segmento_usuario',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='segmento_publicidad',
            name='idPublicidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Publicidad'),
        ),
        migrations.AddField(
            model_name='segmento_publicidad',
            name='idSegmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Segmento'),
        ),
        migrations.AddField(
            model_name='segmento_horario',
            name='idHorario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Horario'),
        ),
        migrations.AddField(
            model_name='segmento_horario',
            name='idSegmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Segmento'),
        ),
        migrations.AddField(
            model_name='segmento',
            name='idEmisora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Emisora'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='idConcursante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Concursante'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='idPregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Pregunta'),
        ),
        migrations.AddField(
            model_name='redsocial_usuario',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redsocial_emisora',
            name='idEmisora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Emisora'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='idEncuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Encuesta'),
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='idHiloChat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.HiloChat'),
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagenes',
            name='segmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Segmento'),
        ),
        migrations.AddField(
            model_name='hilochat',
            name='idEmisora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Emisora'),
        ),
        migrations.AddField(
            model_name='frecuencia_publicidad',
            name='idFrecuencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Frecuencia'),
        ),
        migrations.AddField(
            model_name='frecuencia_publicidad',
            name='idPublicidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Publicidad'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='segmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Segmento'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='idEmisora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Emisora'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='idSegmento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Segmento'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='idPublicidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Publicidad'),
        ),
        migrations.AddField(
            model_name='concurso',
            name='ganador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Concursante'),
        ),
        migrations.AddField(
            model_name='concurso',
            name='idEncuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Encuesta'),
        ),
        migrations.AddField(
            model_name='concursante',
            name='idUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='idPregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Pregunta'),
        ),
    ]
