# Generated by Django 2.1.1 on 2019-02-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0003_auto_20190208_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(default='C', max_length=1),
        ),
    ]
