# Generated by Django 2.1.7 on 2019-02-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0005_auto_20190211_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='isConcurso',
            field=models.BooleanField(default=0),
        ),
    ]
